version: "3"
services:  
  data_modelling:
    container_name: data-modelling-service
    build: "./dataModelling"
    networks:
        - kafka_orenda
networks:
    kafka_orenda:
        external: true


